### ISSUE TITLE
reverse order

### ISSUE THREAD

**Issue by ginberg** [tercen/orderBy_operator#1]
hi @agouy, I would like to have an operator that can do ascending/descending sort (like you implemented) as well as a **reverse** ordering. Is it ok for you to extend this operator? We could change the current 'decreasing' property to a 'ordering_type' property.

**Comment by agouy** [comment]
Hi @ginberg 
Sure it's totally okay to extend this operator, feel free to send a PR if you have something specific in mind.
I'm not sure I understand the difference between using ascending sorting (decreasing = FALSE) and reverse ordering?

**Comment by ginberg** [comment]
hi @agouy, I have added the PR. The reverse ordering just reverses the input rows, it doesn't use the decreasing property. Let me know if you have any questions about it

**Comment by agouy** [comment]
I see now, it totally makes sense to add that. Thanks for putting that together! 
closing the issue

**Comment by ginberg** [comment]
great, thanks for the merge
